### PR TITLE
Compilation tracers

### LINKED ISSUE #7: replace xref with compilation tracers
Currently, we're using [xref](https://hexdocs.pm/mix/Mix.Tasks.Xref.html#calls/1) to collect cross-module references. As @josevalim mentioned in [this comment](https://github.com/elixir-lang/elixir/issues/9322#issuecomment-526926533), starting from Elixir 1.10, it will be more efficient to do this with [compilation tracers](https://hexdocs.pm/elixir/master/Code.html#module-compilation-tracers).

Therefore, it seems that we should base boundaries on top of Elixir `~> 1.10` and use compilation tracers to collect cross-module references.

Looking at the current docs, I'm not completely clear how the usage & the solution would look like. It seems that the client code would have to specify the boundary tracer via
`elixirc_options: [tracers: [Boundary]]`, and then also add the boundary compiler, as it's already done today. The tracer would first collect the xref data, which would then be available to the compiler.

The docs don't seem to go into details of how the tracer should collect the data, but there is a passing suggestion that most of the work should be done asynchronously in other processes. So, one idea which immediately comes to mind is to start up a singleton (i.e. locally registered) process during compilation and stuff the data there (maybe using public named ETS for better throughput). 

However, I'm not sure what happens on recompilation. Suppose I compile a project, and then make a small change which requires recompilation of only one file. I'd expect that in this case we'd receive traces only for that file. If that's correct, it seems we need to persist the data on the disk.

@josevalim could you provide some insight on the following questions:

1. If we're using tracers, the user will have to configure the tracer and the compiler in mix.exs?
2. Collecting data can be done in some singleton BEAM resource (process, ets table)?
3. Do we need to persist this data locally somewhere, to properly handle partial compilations?

### PR DESCRIPTION
**Pull request by sasa1977**
resolves #7 

This is a WIP, but I'd like to have the basic approach reviewed. 

Some notes:

1. The PR is best reviewed one commit at a time.
2. ~~The tracer is included as a sub-dependency. I'm not sure if this will be the final version, but for the moment this approach makes it easy to also run boundary compiler in the boundary lib.~~ In the most recent version, the tracer is included in the boundary, and there's no sub-dependency anymore.
3. ~~The [usage is a bit clumsier](https://github.com/sasa1977/boundary/commit/63b0d9af296a7e709f02cddbb5424b4000952780#diff-41ec5154876c3806520e666f57c8a095R10). A user has to prepend the `:boundary_xref` compiler and append the `:boundary` compiler.~~ Also fixed, owing to the new `after_compiler` mechanism.
4. ~~The approach is not 100% bulletproof. If a user abruptly terminates the compiler, we might end up losing some data, and that data loss might be silent and implicit. During subsequent compilations, we might e.g. miss some errors, because we didn't persist all calls to disk.~~ Shouldn't be the case, since files are saved only if compilation succeeds.
5. No performance analysis has been done.
6. CI is failing, because we're now depending on 1.10-dev, which is not supported. This PR won't be merged before 1.10 is released.

### CODE REVIEW

**Comment by josevalim** [comment]
3. I added a Mix.Task.Compiler.after_compile or similar callback so you can register a function that runs later, so you don't need to prepend/append.

4. Ideally you would persist things only in the after_compile pass, so any intermediate result, errors during compilation, etc, are not persisted.

**Comment by sasa1977** [comment]
>     1. I added a Mix.Task.Compiler.after_compile or similar callback so you can register a function that runs later, so you don't need to prepend/append.

I'm already using `after_compile` to do some final cleanup. However, from what I can see, I can't return compilation errors from `after_compile`, right?

The thing is that `boundary` is currently a compiler,so it can report boundary errors as compilation errors. This gives it nice integration with ElixirLS:

image

From what I understand, if I decide to do boundary checks in `after_compile`, I won't be able to achieve this, right?

>     2. Ideally you would persist things only in the after_compile pass, so any intermediate result, errors during compilation, etc, are not persisted.

That makes the thing even less reliable, because we're postponing persistence even further. I'm sort of fine with this, but just wanted to note that I think that the tracer approach has some inconsistency problems, simply b/c the compiler might save the beam file, and then crash (or be killed) before the tracer is able to save the traces. On next recompilation, that beam won't be compiled, and we work with inconsistent data.

**Comment by josevalim** [comment]
Good feedback. I will change after_compile to allow running  like any other compiler or maybe figure out a way to add compilers dynamically.

The Elixir compiler does not save files unless the whole compilation finishes, so the inconsistency you describe should not happen. I guess it can happen only if a later compiler fails... that ties in to the after_compile issue above. What if we allow the after_compile to be registered for a given compiler? So you can do something after the elixir compiler, and change the elixir compiler to add your own warnings and errors. This should address all these problems.

The only other inconsistency you have to take care is that you need to check if .beam files were removed. Not sure how much of an issue this is.

**Comment by sasa1977** [comment]
> I will change after_compile to allow running like any other compiler or maybe figure out a way to add compilers dynamically.

Thanks! Either would be very welcome :-)

> The Elixir compiler does not save files unless the whole compilation finishes, so the inconsistency you describe should not happen.

This also sounds great! As long as the files are not saved before `after_compile` finishes, I think we're good.

> What if we allow the after_compile to be registered for a given compiler? So you can do something after the elixir compiler, and change the elixir compiler to add your own warnings and errors. This should address all these problems.

The thing is that the first compiler has to setup the tracer, and then I want to execute the analysis after all other compilers are done. So, I want to register something which is executed after all subsequent compilers, and add warnings/errors.

> The only other inconsistency you have to take care is that you need to check if .beam files were removed. Not sure how much of an issue this is.

I'm already handling this. The second compiler is the one doing the analysis. This compiler loads the app, and then sends the list of app modules, and the tracer code then deletes the obsolete ones from the database (local dets). If you have a better suggestion, I'm all ears :-)

Thanks for cooperating on this!

**Comment by josevalim** [comment]
You could add something after the Elixir compiler for persisting and after the app compiler for validating. But honestly, I think after the Elixir compiler should be enough for both, you would just need to “ls” the ebin directory to see if any modules were removed.

**Comment by josevalim** [comment]
after_compile/1 has now become after_compiler/2 and it expects a compiler name (such as `:elixir`) and the function now receives a tuple, with the status and diagnostics. So now you can change the status and/or add your own diagnostics.

**Comment by sasa1977** [comment]
Thanks! I'll take a look and report back.

**Comment by josevalim** [comment]
Btw, we should have a release candidate out in a week or two, so ideally we need to make sure everything is working as expected before then. :) But in the worst case scenario we can make some changes after the RC is out (but before final!).

**Comment by sasa1977** [comment]
Thnx for letting me know, I'll do my best to test it out before that!

**Comment by sasa1977** [comment]
@josevalim I've given this a try, and it seems to work exactly as expected. Clients now have to register boundary as the first compiler, and we correctly report boundary errors. I'll try to do some more tests when I find the time, but I'd say that the contract seems solid, which is I think the most important thing.

I'm still using `after_compiler(:app, ...)`, because I need to load the app anyway, since I'm looking up module attributes to get boundaries definitions, and also to figure out if a module implements a protocol. I guess this could be handled without loading the app, for example by manually loading beam modules from the project path, or maybe even by handling compiler trace events. However, it feels like the implementation would be significantly more complex, and I'm not sure what would be the benefits here. If you have some thoughts on this let me know.

Thanks for helping out!

**Comment by josevalim** [comment]
I think you can get all modules by simply reading from ebin, which is what
compile.app does. And from my understanding, you already read said
directory to detect removed files? In any case, both ways work, so I am
glad everything is working as expected. Thank for the updates!
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Pull request merged**
